language: cpp

env:
  - MATRIX_EVAL="CC=gcc-8 CXX=g++-8" CONFIG=Release VCPKG_DEFAULT_TRIPLET=x64-linux VCPKG_TARGET_TRIPLET=x64-linux
  - MATRIX_EVAL="CC=gcc-8 CXX=g++-8" CONFIG=Debug VCPKG_DEFAULT_TRIPLET=x64-linux VCPKG_TARGET_TRIPLET=x64-linux

matrix:
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8

before_install:
  - eval "${MATRIX_EVAL}"
  - mkdir $HOME/usr
  - export PATH="$HOME/usr/bin:$PATH"
  - export CMAKE_INSTALL_SCRIPT=cmake-3.15.0-Linux-x86_64.sh
  - wget https://github.com/Kitware/CMake/releases/download/v3.15.0/${CMAKE_INSTALL_SCRIPT}
  - chmod +x ${CMAKE_INSTALL_SCRIPT}
  - ./${CMAKE_INSTALL_SCRIPT} --prefix=$HOME/usr --exclude-subdir --skip-license

install:
  - mkdir -p ${HOME}/vcpkg

  - set -e
  - pushd ${HOME}/vcpkg
  - git init
  - git remote add origin https://github.com/Microsoft/vcpkg.git
  - git fetch origin master
  - git checkout -b master origin/master
  - ./bootstrap-vcpkg.sh
  - ./vcpkg install mongo-c-driver
  - ./vcpkg integrate install
  - popd

script:
  - set -e
  - mkdir -p build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=${CONFIG} -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE} -DVCPKG_TARGET_TRIPLET=${VCPKG_TARGET_TRIPLET} ..
  - make -j
  - cd ..

cache:
  directories:
    - ${HOME}/vcpkg/installed