language: cpp

env:
  global:
    - MATRIX_EVAL="CC=gcc-8 CXX=g++-8"
    - VCPKG_DEFAULT_TRIPLET=x64-linux
    - VCPKG_TARGET_TRIPLET=x64-linux
    - CMAKE_TOOLCHAIN_FILE=${HOME}/vcpkg/scripts/buildsystems/vcpkg.cmake

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-8

dist: xenial

matrix:
  include:
    - os: linux
      env: CONFIG=Debug
    - os: linux
      env: CONFIG=Release


before_install:
  - eval "${MATRIX_EVAL}"
  - mkdir $HOME/usr
  - export PATH="$HOME/usr/bin:$PATH"
  - export CMAKE_INSTALL_SCRIPT=cmake-3.15.0-Linux-x86_64.sh
  - wget https://github.com/Kitware/CMake/releases/download/v3.15.0/${CMAKE_INSTALL_SCRIPT}
  - chmod +x ${CMAKE_INSTALL_SCRIPT}
  - ./${CMAKE_INSTALL_SCRIPT} --prefix=$HOME/usr --exclude-subdir --skip-license

install:
  - mkdir -p ${HOME}/vcpkg

  - set -e
  - pushd ${HOME}/vcpkg
  - git init
  - git remote add origin https://github.com/Microsoft/vcpkg.git
  - git fetch origin master
  - git checkout -b master origin/master
  - ./bootstrap-vcpkg.sh
  - ./vcpkg install mongo-c-driver
  - ./vcpkg integrate install
  - popd

script:
  - set -e
  - mkdir -p build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=${CONFIG} -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE} -DVCPKG_TARGET_TRIPLET=${VCPKG_TARGET_TRIPLET} ..
  - make -j
  - cd ..

cache:
  directories:
    - ${HOME}/vcpkg/installed

deploy:
  provider: releases
  api_key:
    secure: "hCSEMoyy9d38EUxEqQKByHNuyqIkOyBDa9xicZvjG88/1L8NBo/e5i1QdBwSNM8VjvMKi38eFSVlW4cxtPZCx3JwWTxl4on/VfgXfYf0CpKtrNdZ/Oofxw7Z9kr+lBZZc7h4PqExt0f60003JG8uQvZN2goPLcsLZdER2Vr4mOjTZS590k+Kn8Za1YQqXgezKhaMA6u3m1ZNN3TEbPCaY7xqBjsboTFKRJPj0mntNatpJspZc5cIJobvsVugebHUoNO/RnfvkbU/rbSLqbsiJZKXucwLO/xWQgPOFJ5h9Vynhas9ugXehr/Ymgpa0yMK9XX3btHTBvdCxGs8vu7ZuDkuY2iiLcFhgMvfSzkJvQq56HsUn1JWmyO1qhwClaaAUlwGMHAyiIaWJaYn8DgQ7Mcr+Ljz1pFYG5dwAUsAxTjIj8gcX8bbBXhMqymnpMnSQu9ZpBZt9RV01o7aRaSR07nmGvsuvv7FPtrrnib4yWtOA+DtM6tCREUbi0Yhq90Pg5MIlpB1ZRget8kiI3KBkC32TbEBSV9esYjvaFwKAvyBIJEmHYmNCKLoEU2enOR4aQXyb3fYaOlzJvXffVp8zfrlhpf3NwvJMPIsOlPm005nR2o+6puClxGSWSofCP+j5xf+1XQDSCk7A6rmRbi5/cFR5uhItUJMDIZZMDs0Gb4="
  file_glob: true
  file: build/**/*.dll
  skip_cleanup: true
  draft: true
  on:
    tags: true
    condition: $CONFIG = Release