language: cpp

env:
  global:
    - MATRIX_EVAL="CC=gcc-8 CXX=g++-8"
    - VCPKG_DEFAULT_TRIPLET=x64-linux
    - VCPKG_TARGET_TRIPLET=x64-linux
    - CMAKE_TOOLCHAIN_FILE=${HOME}/vcpkg/scripts/buildsystems/vcpkg.cmake

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-8

dist: xenial

matrix:
  include:
    - os: linux
      env: CONFIG=Debug
    - os: linux
      env: CONFIG=Release

before_install:
  - eval "${MATRIX_EVAL}"
  - mkdir $HOME/usr
  - export PATH="$HOME/usr/bin:$PATH"
  - export CMAKE_INSTALL_SCRIPT=cmake-3.15.0-Linux-x86_64.sh
  - wget https://github.com/Kitware/CMake/releases/download/v3.15.0/${CMAKE_INSTALL_SCRIPT}
  - chmod +x ${CMAKE_INSTALL_SCRIPT}
  - ./${CMAKE_INSTALL_SCRIPT} --prefix=$HOME/usr --exclude-subdir --skip-license

install:
  - mkdir -p ${HOME}/vcpkg

  - set -e
  - pushd ${HOME}/vcpkg
  - git init
  - git config remote.origin.url >&- || git remote add origin https://github.com/Microsoft/vcpkg.git
  - git fetch origin master
  - git checkout master 2>/dev/null || git checkout -b master origin/master
  - ./bootstrap-vcpkg.sh
  - ./vcpkg install mongo-c-driver
  - ./vcpkg integrate install
  - popd

script:
  - set -e
  - mkdir -p build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=${CONFIG} -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE} -DVCPKG_TARGET_TRIPLET=${VCPKG_TARGET_TRIPLET} ..
  - make -j
  - cd ..

cache:
  directories:
    - ${HOME}/vcpkg/

deploy:
  provider: releases
  api_key:
    secure: "dQR0qwIsbu2zPdf0BLBuAX6BcrORCZePAMp80Noeysl7jDHm71WP7LbGHJXPYePmTOAY8DYZfarzSLCKZCbDq0YWkYn+cgQIh2bhSNEWTnazRwAxrt8R95ZLE5eV5RA47tEhzv3vibdYmarUm0fMKGA/0y5NBKe3coUjmAZwNukrAm+T9U/jv6dnOQW6CNptk0oMovJ2BTgrc72nVDP6iVAED4j8if2QH6uHFAgV4H7tWSj17nlAR8VB/8mp9mQmbHqY970DUMMjz6c3lQM6aUWjAPJMCCy33XjJVypJohv+dYyh16mrxEmLdzpco9RWz8TD5BcdoNhzHuPP5Wapi6ScHpey3zhfe+2bZiSx0TNRo8xCvGmvTy95dXEeojCMVdqyyhFMcR4lYReLTfurdr8yCmKSrWiK8GvoxRR9D+SaqJdrNBGDpuh9dZKR1Jz4VPtNsvZvWmGyUqMLgt+oR8t6nt5Ti6rBLGhBdQZJYBTgYuTUYzDiuuKMTixOKjya8Oq1Z0nWQougLKj20eshhXPe3YqQEAnKvQtQy+/b3b6LhbYvZL4GLzgnl616pO1SJA+LsIerGxgp0U27eJxsSZJuQ+RReh2oQhE5yJjJgJ7JBXs4AsK7Lq3110s4+pRHue5Dfw63Pq5u4zWn6l7QSlV2TCX3KwV5mQ6thNV3zD8="
  file_glob: true
  file: build/**/*.dll
  skip_cleanup: true
  draft: true
  on:
    tags: true
    condition: $CONFIG = Release