platform: x64

image:
  - Visual Studio 2019

environment:
  VCPKG_DEFAULT_TRIPLET: x64-windows-static
  VCPKG_TARGET_TRIPLET: x64-windows-static
  CMAKE_TOOLCHAIN_FILE: C:\Tools\vcpkg\scripts\buildsystems\vcpkg.cmake

configuration:
  - Debug
  - Release

install:
  - vcpkg remove --outdated --recurse
  - vcpkg install mongo-c-driver
  - vcpkg integrate install

  - cd %APPVEYOR_BUILD_FOLDER%

build_script:
  - mkdir build
  - cd build

  - cmake -DCMAKE_BUILD_TYPE=%configuration% -DCMAKE_TOOLCHAIN_FILE=%CMAKE_TOOLCHAIN_FILE% -DVCPKG_TARGET_TRIPLET=%VCPKG_TARGET_TRIPLET% ..
  - cmake --build . --target ALL_BUILD --config %configuration%

cache:
  - C:\Tools\vcpkg\installed\ -> .appveyor.yml
