platform: x64

image:
  - Visual Studio 2019
  - Ubuntu

environment:
  APPVEYOR_YML_DISABLE_PS_LINUX: true
  VCPKG_DEFAULT_TRIPLET: x64-windows-static
  VCPKG_TARGET_TRIPLET: x64-windows-static
  CMAKE_TOOLCHAIN_FILE: "C:\Tools\vcpkg\scripts\buildsystems\vcpkg.cmake"

configuration:
  - Debug
  - Release

for:
  -
    matrix:
      only:
        - image: Ubuntu
    environment:
      VCPKG_DEFAULT_TRIPLET: x64-linux
      VCPKG_TARGET_TRIPLET: x64-linux
      CMAKE_TOOLCHAIN_FILE: "%APPVEYOR_BUILD_FOLDER%/vcpkg/scripts/buildsystems/vcpkg.cmake"

install:
  # Windows
  - ps: cd C:\tools\vcpkg
  - ps: git pull
  - ps: .\bootstrap-vcpkg.bat

  # Linux
  - sh: git clone https://github.com/Microsoft/vcpkg.git
  - sh: cd vcpkg
  - sh: ./bootstrap-vcpkg.sh

  - vcpkg remove --outdated --recurse
  - vcpkg install mongo-c-driver
  - vcpkg integrate install

  - cd "%APPVEYOR_BUILD_FOLDER%"

build_script:
  - cmd: mkdir build && cd build

  - cmake -DCMAKE_BUILD_TYPE=%configuration% -DCMAKE_TOOLCHAIN_FILE=%CMAKE_TOOLCHAIN_FILE% -DVCPKG_TARGET_TRIPLET=%VCPKG_TARGET_TRIPLET% ..
  - cmake --build . --target all
