platform: x64

image:
  - Visual Studio 2019
  - Ubuntu

environment:
  VCPKG_DEFAULT_TRIPLET: x64-windows-static
  VCPKG_TARGET_TRIPLET: x64-windows-static
  CMAKE_TOOLCHAIN_FILE: C:\Tools\vcpkg\scripts\buildsystems\vcpkg.cmake

configuration:
  - Debug
  - Release

for:
  -
    matrix:
      only:
        - image: Ubuntu
    environment:
      VCPKG_DEFAULT_TRIPLET: x64-linux
      VCPKG_TARGET_TRIPLET: x64-linux
      CMAKE_TOOLCHAIN_FILE: "%APPVEYOR_BUILD_FOLDER%/vcpkg/scripts/buildsystems/vcpkg.cmake"

install:
  # Linux
  - sh: git clone https://github.com/Microsoft/vcpkg.git
  - sh: cd vcpkg
  - sh: ./bootstrap-vcpkg.sh

  - vcpkg remove --outdated --recurse
  - vcpkg install mongo-c-driver
  - vcpkg integrate install

  - ps: cd $env:APPVEYOR_BUILD_FOLDER

build_script:
  - mkdir build

  - ps: cd build
  - ps: cmake -DCMAKE_BUILD_TYPE=$env:configuration% -DCMAKE_TOOLCHAIN_FILE=$env:CMAKE_TOOLCHAIN_FILE% -DVCPKG_TARGET_TRIPLET=$env:VCPKG_TARGET_TRIPLET% ..
  - ps: cmake --build . --target all
